apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: walmartpayment-dev
  namespace: walmartdev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: walmartpayment-dev
  minReplicas: 1
  maxReplicas: 10
  metrics:
    type: Resource
    resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 20
